version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

sphinx:
   configuration: docs/conf.py
   builder: html
   fail_on_warning: false

python:
   install:
     - method: pip
       path: golf_federated/
     - requirements: requirements_dev.txt
     - requirements: docs/requirements_dev.txt